name: Formatter

on:
  pull_request:
  push:

jobs:
  Formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
      - uses: isort/isort-action@v1.1.0
        with:
          configuration: "--settings-file=.isort.cfg"
          requirements-files: "requirements.txt"
      - uses: psf/black@stable
        with:
          options: "--line-length=120"
          version: "24.2.0"
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Format code with isort and black"
